kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mx-server
  labels:
    component: mx-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClassName }}
