# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mx-server
  labels:
    app: mx-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
   app: mx-server
